# Generated by Django 5.0.6 on 2024-06-08 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacjaBaza', '0006_rename_pointsforquestion_questions_points_for_question_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmembers',
            name='group',
        ),
        migrations.RemoveField(
            model_name='groupmembers',
            name='users',
        ),
        migrations.DeleteModel(
            name='Answers',
        ),
        migrations.DeleteModel(
            name='Groups',
        ),
        migrations.DeleteModel(
            name='GroupMembers',
        ),
    ]
